name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
      - name: Install toolchain
        run: aftman install --no-trust-check
      - name: Format check
        run: stylua --check src test example
      - name: Lint
        run: selene src test example
      - name: Wally install
        run: wally install
      - name: Package validation
        run: wally package --list
      - name: Unit tests
        run: lune run test/run.luau
      - name: Rojo build
        run: rojo build default.project.json --output PathfindingPlus.rbxlx
